spring:
  autoconfigure:
    exclude:
      - 'org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration'
      - 'org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration'
  application:
    name: 'api'
  mvc:
    dispatch-options-request: true
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: '2KB'
      max-file-size: '100MB'
      max-request-size: '100MB'
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    name: 'e-shop-pet'
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        jdbc:
          time_zone: 'UTC'
    hibernate:
      ddl-auto: 'none'
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: 'public'
    validate-on-migrate: false
    user: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    out-of-order: true

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: '/api'

jwt:
  secret:
    access: 'aWxzZGdmaWhzZ2FkaWxmaGRhaXNoZm9kaHNhbGt2aGl1ZHNoYXVzaGRmb3VoYWlsdXNkaGZsaWRzaGFmZ3NpdWFoZGZpdWhkbGtzaGZnZHNpYWd2aXlhZWl1ZGZobGl1ZGhhbGl1ZmhsZHNoYWZpaHNsamtkZmhzZGtnZnlzZGd1eXZnaWRpbGhha2hmbGtoYXNkbGtqZmhoamtnamtoZ2poZ2RhZmhzamdmZGdzYW95Z2Z5ZGd1aHZoZGJhbGpiYnZkYWl1c2hoO29pd2lvc2phZG5mbGtqZHNsYWZsaXNhZGp2a2pka2Jza2poZmxrbGJzamxobGFramhhZ2l1Y2hlZHNsaGFvaGZkb2loc2Fsa2hjYWtqYmNvaXdoYW9pZmhmYWpoZ2toYw=='

security:
  api-key: 'dummy-api-key'

logging:
  level:
    gaiduchek.maksym.api: TRACE
    # org.springframework: TRACE

feign:
  security:
    url: 'http://localhost:8090/security'
